# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRecord',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u540d\u5b57')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='\u8eab\u9ad8')),
                ('bd_index', models.IntegerField(blank=True, null=True, verbose_name='\u767e\u5ea6\u6307\u6570')),
            ],
        ),
    ]
