# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20170310_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='personrecord',
            name='all_props',
            field=models.BinaryField(blank=True, null=True, verbose_name='\u6240\u6709\u5c5e\u6027'),
        ),
    ]
