# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_personrecord_all_props'),
    ]

    operations = [
        migrations.AddField(
            model_name='personrecord',
            name='updated',
            field=models.NullBooleanField(),
        ),
    ]
