# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_personrecord_zy'),
    ]

    operations = [
        migrations.AddField(
            model_name='personrecord',
            name='qsny',
            field=models.DateField(blank=True, null=True, verbose_name='\u53bb\u4e16\u5e74\u6708'),
        ),
    ]
