# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_personrecord_qsny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personrecord',
            name='updated',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
