# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20170312_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='personrecord',
            name='name_shuli',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u91d1\u699c\u6570\u7406'),
        ),
    ]
