# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_personrecord_name_shuli'),
    ]

    operations = [
        migrations.AddField(
            model_name='personrecord',
            name='english_info',
            field=models.TextField(blank=True, null=True, verbose_name='\u82f1\u6587\u540d\u8bcd\u5178'),
        ),
    ]
