# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_personrecord_english_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonEnglishNames',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u82f1\u6587\u540d')),
                ('sex', models.BooleanField()),
                ('sex_count', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
