# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_commonenglishnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonenglishnames',
            name='sex',
            field=models.NullBooleanField(),
        ),
    ]
