# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_auto_20170731_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlcontent',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
