# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlcontent',
            name='corrupted',
            field=models.BooleanField(default=False),
        ),
    ]
