# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_auto_20170731_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='htmlcontent',
            name='exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='htmlcontent',
            name='has_names',
            field=models.NullBooleanField(),
        ),
        migrations.AlterUniqueTogether(
            name='name',
            unique_together=set([('name', 'title')]),
        ),
        migrations.AlterIndexTogether(
            name='name',
            index_together=set([('name', 'title')]),
        ),
    ]
