# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0018_auto_20170801_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
