# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0020_proxy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together=set([('ip', 'port')]),
        ),
        migrations.AlterIndexTogether(
            name='proxy',
            index_together=set([('ip', 'port')]),
        ),
    ]
