# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0021_auto_20180508_0734'),
    ]

    operations = [
#         migrations.AddField(
#             model_name='proxy',
#             name='created_time',
#             field=models.DateTimeField(auto_now=True),
#         ),
    ]
