# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0022_proxy_created_time'),
    ]

    operations = [
#         migrations.DeleteModel(
#             name='Proxy',
#         ),
    ]
