# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0025_delete_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('port', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=6)),
                ('total', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together=set([('ip', 'port')]),
        ),
        migrations.AlterIndexTogether(
            name='proxy',
            index_together=set([('ip', 'port')]),
        ),
    ]
