# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0026_auto_20180508_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
