# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0027_proxy_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
