# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0028_auto_20180508_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='json',
            field=models.TextField(default='[]'),
        ),
    ]
