# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0029_proxy_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='rrate',
            field=models.FloatField(default=0, verbose_name='\u8fd1\u671f\u6210\u529f\u7387'),
        ),
    ]
