# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='names',
            unique_together=set([('name', 'title')]),
        ),
        migrations.AlterIndexTogether(
            name='names',
            index_together=set([('name', 'title')]),
        ),
    ]
