# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='eid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='names',
            name='hid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
