# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='obj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='obj', to='mind.Element'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set([('sub', 'pred', 'obj')]),
        ),
        migrations.AlterIndexTogether(
            name='relation',
            index_together=set([('sub', 'pred', 'obj')]),
        ),
    ]
