# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0002_auto_20180423_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='tag',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u6210\u7acb'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj', to='mind.Element', verbose_name='\u5bbe'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='pred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pred', to='mind.Element', verbose_name='\u8c13'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='mind.Element', verbose_name='\u4e3b'),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set([('sub', 'pred', 'obj', 'tag')]),
        ),
        migrations.AlterIndexTogether(
            name='relation',
            index_together=set([('sub', 'pred', 'obj', 'tag')]),
        ),
    ]
